/:
  controller: Main
  action: home

/register:
  controller: User
  action: register

/login:
  controller: User
  action: login

/reset:
  controller: User
  action: reset

/feed:
  controller: User
  action: feed

/forgot:
  controller: User
  action: forgot


