/:
  controller: Main
  action: home

/register:
  controller: User
  action: register

/login:
  controller: User
  action: login

/logout:
  controller: User
  action: logout

/reset:
  controller: User
  action: reset

/feed:
  controller: Main
  action: feed

/forgot:
  controller: User
  action: forgot

/groupsmng:
  controller: Group
  action: groupsmng

/upload:
  controller: Photo
  action: upload


